sonar.projectKey=gge-tracker_gge-tracker
sonar.organization=gge-tracker

sonar.sources=.

sonar.tests=empire-api/tests,gge-tracker-backend-api/tests,gge-tracker-internal-scraping/tests

sonar.exclusions=database/**,gge-tracker-tools/**,gge-tracker-fetcher/**,monitoring/**,\
  empire-api/tests/**,gge-tracker-backend-api/tests/**,gge-tracker-internal-scraping/tests/**,\
  **/node_modules/**,**/dist/**,**/coverage/**,**/*.min.js
sonar.cpd.exclusions=**/eslint.config.*,\
  **/temp-server-events.config.ts,**/temporary-server-events.config.ts,\
  **/release-notes.component.ts
sonar.javascript.node.maxspace=8192

sonar.issue.ignore.multicriteria=cssContrast,scrapingInternalHttp
sonar.issue.ignore.multicriteria.cssContrast.ruleKey=css:S7924
sonar.issue.ignore.multicriteria.cssContrast.resourceKey=**/*
sonar.issue.ignore.multicriteria.scrapingInternalHttp.ruleKey=typescript:S5332
sonar.issue.ignore.multicriteria.scrapingInternalHttp.resourceKey=gge-tracker-internal-scraping/src/**
