//                                   __                        __
//    ____   ____   ____           _/  |_____________    ____ |  | __ ___________
//   / ___\ / ___\_/ __ \   ______ \   __\_  __ \__  \ _/ ___\|  |/ // __ \_  __ \
//  / /_/  > /_/  >  ___/  /_____/  |  |  |  | \// __ \\  \___|    <\  ___/|  | \/
//  \___  /\___  / \___  >          |__|  |__|  (____  /\___  >__|_ \\___  >__|
// /_____//_____/      \/                            \/     \/     \/    \/
//
//  Copyrights (c) 2025 - gge-tracker.com & gge-tracker contributors
//
export type Castle = [number, number, number];

export type MovementType = 'add' | 'remove' | 'move';

export interface PlayerDatabase {
  playerId: number;
  allianceId: number | null;
  playerName: string;
  allianceName: string | null;
  castles: Castle[];
}

export interface CastleMovement {
  player_id: number;
  castle_type: number;
  movement_type: MovementType;
  position_x_old?: number;
  position_y_old?: number;
  position_x_new?: number;
  position_y_new?: number;
}

export interface DungeonMap {
  coordinates: [number, number];
  time: number;
  playerId: number;
  updatedAt: Date;
}

export type HighScoreKey = (typeof HIGH_SCORE_KEYS)[number];
export const HIGH_SCORE_KEYS = [
  'ALIEN_INVASIONALIEN_INVASION',
  'ALLIANCE_ALIEN_INVASION_ALLIANCE',
  'ALLIANCE_ALIEN_INVASION_PLAYER',
  'ALLIANCE_AQUA_POINTS',
  'ALLIANCE_BATTLE_GROUND_ALLIANCE_COLLECTOR',
  'ALLIANCE_BATTLE_GROUND_ALLIANCE_TOWER',
  'ALLIANCE_BATTLE_GROUND_HIGHSCORE_NUMBER_OF_ENTRIES_SHOWN',
  'ALLIANCE_BATTLE_GROUND_PLAYER_COLLECTOR',
  'ALLIANCE_BATTLE_GROUND_PLAYER_TOWER',
  'ALLIANCE_BATTLE_GROUND_PREVIOUS_RUN_ALLIANCE',
  'ALLIANCE_BATTLE_GROUND_PREVIOUS_RUN_PLAYER',
  'ALLIANCE_BUILDINGS',
  'ALLIANCE_DAIMYO',
  'ALLIANCE_HONOR',
  'ALLIANCE_KINGDOMS_LEAGUE_SEASON',
  'ALLIANCE_KINGDOMS_LEAGUE_SEASON_EVENT',
  'ALLIANCE_LANDMARKS',
  'ALLIANCE_MIGHT_POINTS',
  'ALLIANCE_MOBILISATION_EVENT',
  'ALLIANCE_NOMADINVASION_ALLIANCE',
  'ALLIANCE_NOMADINVASION_PLAYER',
  'ALLIANCE_RED_ALIEN_INVASION_ALLIANCE',
  'ALLIANCE_RED_ALIEN_INVASION_PLAYER',
  'ALLIANCE_SAMURAI_ALIEN_INVASION_ALLIANCE',
  'ALLIANCE_SAMURAI_ALIEN_INVASION_PLAYER',
  'ALLIANCE_TOURNAMENT_FAME',
  'ANNIVERSARY_GACHA_EVENT',
  'AQUAPOINTS_NUM_ENTRIES',
  'BEGGING_KNIGHTS',
  'BLACK_FRIDAY_GACHA_EVENT',
  'CHRISTMAS_GACHA_EVENT',
  'COLOSSUS',
  'DAIMYO_NUMBER_OF_ENTRIES_SHOWN',
  'DECO_GACHA_EVENT',
  'DONATION_EVENT',
  'DONATION_EVENT_NUMBER_OF_ENTRIES',
  'EASTER_GACHA_EVENT',
  'FACTION_INVASION_ALLIANCE',
  'FACTION_INVASION_INITIAL_POINTS',
  'FACTION_INVASION_PLAYER_BLUE',
  'FACTION_INVASION_PLAYER_RED',
  'FACTION_TOURNAMENT',
  'GLOBALSERVER_PREVIOUS_RUN_HIGHSCORES_ON_MAINSERVER',
  'GLOBAL_SERVER_PREVIOUS_RUN_NUMBER_OF_ENTRIES_SHOWN',
  'HALLOWEEN_GACHA_EVENT',
  'INITIAL_HIGHSCORE_SIZE_ON_LIVE',
  'INITIAL_HIGHSCORE_SIZE_ON_TEST',
  'INVALID_RANK',
  'KINGDOMS_LEAGUE_SEASON',
  'KINGDOMS_LEAGUE_SEASON_EVENT',
  'LEAGUED_HIGHSCORES',
  'LONG_TERM_POINT_EVENT',
  'LUCKY_WHEEL',
  'LUCKY_WHEEL_SALE_DAYS',
  'MIN_XP_FOR_HIGHSCORE',
  'NOMADINVASION',
  'NO_ENTRIES',
  'NO_OFFSET',
  'NO_SCORE',
  'NUMBER_OF_ENTRIES_SHOWN',
  'NUMBER_OF_ENTRIES_SHOWN_FOR_COLOSS',
  'NUMBER_OF_ENTRIES_SHOWN_FOR_FACTION',
  'PERSISTENT_LEAGUE_NUMBER_OF_ENTRIES_SHOWN',
  'PLAYER_ACHIEVEMENT_POINTS',
  'PLAYER_BUILDINGS',
  'PLAYER_HONOR',
  'PLAYER_LEGEND',
  'PLAYER_MIGHT_POINTS',
  'PLAYER_WEEKLY_LOOT',
  'POINTS_CAPITALS',
  'POINTS_KINGS_TOWER',
  'POINTS_LABORATORY',
  'POINTS_METROPOL',
  'POINTS_MONUMENTS',
  'POINT_EVENT',
  'RANK_ONE',
  'SAMURAI_ALLIANCE',
  'SAMURAI_PLAYER',
  'SEASON_NUMBER_OF_ENTRIES_SHOWN',
  'SUMMER_GACHA_EVENT',
  'TEMPSERVER_PREVIOUS_RUN_PLAYER',
  'TEMP_SERVER_DAILY_COLLECTOR_POINTS',
  'TEMP_SERVER_DAILY_MIGHT_POINTS_BUILDINGS',
  'TEMP_SERVER_DAILY_RANK_SWAP',
  'TEMP_SERVER_GLOBAL',
  'TEMP_SERVER_HIGHSCORE_NUMBER_OF_ENTRIES_SHOWN',
  'TITLE_COOLDOWN',
  'TITLE_COOLDOWN_TEST',
  'TOURNAMENT_FAME',
  'TOURNAMENT_NUM_ENTRIES',
  'TOURNAMENT_START_OFFSET',
  'TOURNAMENT_TOP',
] as const;
