auth_enabled: false

server:
  http_listen_port: 3100
  log_level: warn

common:
  path_prefix: /tmp/loki
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1

schema_config:
  configs:
    - from: 2023-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/cache
    shared_store: filesystem
  filesystem:
    directory: /tmp/loki/chunks

ingester:
  wal:
    enabled: true
    dir: /tmp/loki/wal
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  max_chunk_age: 1h

querier:
  engine:
    timeout: 1m
  query_timeout: 1m

query_range:
  align_queries_with_step: true
  max_retries: 5
  cache_results: true

frontend:
  log_queries_longer_than: 5s
  compress_responses: true

limits_config:
  retention_period: 168h
  split_queries_by_interval: 15m
