import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class RankingService {
  public isInLoading = true;

  public readonly CHART_LOCALES = [
    {
      name: 'fr',
      options: {
        months: [
          'Janvier',
          'Février',
          'Mars',
          'Avril',
          'Mai',
          'Juin',
          'Juillet',
          'Août',
          'Septembre',
          'Octobre',
          'Novembre',
          'Décembre',
        ],
        shortMonths: ['Jan', 'Fév', 'Mar', 'Avr', 'Mai', 'Juin', 'Juil', 'Août', 'Sep', 'Oct', 'Nov', 'Déc'],
        days: ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'],
        shortDays: ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
        toolbar: {
          exportToSVG: 'Télécharger en SVG',
          exportToPNG: 'Télécharger en PNG',
          exportToCSV: 'Télécharger en CSV',
          menu: 'Menu',
          selection: 'Sélection',
          selectionZoom: 'Sélectionner une zone',
          zoomIn: 'Zoom avant',
          zoomOut: 'Zoom arrière',
          pan: 'Déplacer',
          reset: 'Réinitialiser le zoom',
        },
      },
    },
    {
      name: 'en',
      options: {
        months: [
          'January',
          'February',
          'March',
          'April',
          'May',
          'June',
          'July',
          'August',
          'September',
          'October',
          'November',
          'December',
        ],
        shortMonths: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
        days: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        shortDays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
        toolbar: {
          exportToSVG: 'Download SVG',
          exportToPNG: 'Download PNG',
          exportToCSV: 'Download CSV',
          menu: 'Menu',
          selection: 'Selection',
          selectionZoom: 'Selection Zoom',
          zoomIn: 'Zoom In',
          zoomOut: 'Zoom Out',
          pan: 'Panning',
          reset: 'Reset Zoom',
        },
      },
    },
    {
      name: 'de',
      options: {
        months: [
          'Januar',
          'Februar',
          'März',
          'April',
          'Mai',
          'Juni',
          'Juli',
          'August',
          'September',
          'Oktober',
          'November',
          'Dezember',
        ],
        shortMonths: ['Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez'],
        days: ['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'],
        shortDays: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
        toolbar: {
          exportToSVG: 'SVG speichern',
          exportToPNG: 'PNG speichern',
          exportToCSV: 'CSV speichern',
          menu: 'Menü',
          selection: 'Auswahl',
          selectionZoom: 'Auswahl vergrößern',
          zoomIn: 'Vergrößern',
          zoomOut: 'Verkleinern',
          pan: 'Verschieben',
          reset: 'Zoom zurücksetzen',
        },
      },
    },
    {
      name: 'nl',
      options: {
        months: [
          'Januari',
          'Februari',
          'Maart',
          'April',
          'Mei',
          'Juni',
          'Juli',
          'Augustus',
          'September',
          'Oktober',
          'November',
          'December',
        ],
        shortMonths: ['Jan', 'Feb', 'Maa', 'Apr', 'Mei', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dec'],
        days: ['Zondag', 'Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag'],
        shortDays: ['Zo', 'Ma', 'Di', 'Wo', 'Do', 'Vr', 'Za'],
        toolbar: {
          exportToSVG: 'SVG downloaden',
          exportToPNG: 'PNG downloaden',
          exportToCSV: 'CSV downloaden',
          menu: 'Menu',
          selection: 'Selectie',
          selectionZoom: 'Inzoomen op selectie',
          zoomIn: 'Inzoomen',
          zoomOut: 'Uitzoomen',
          pan: 'Verslepen',
          reset: 'Zoom herstellen',
        },
      },
    },
    {
      name: 'ro',
      options: {
        months: [
          'Ianuarie',
          'Februarie',
          'Martie',
          'Aprilie',
          'Mai',
          'Iunie',
          'Iulie',
          'August',
          'Septembrie',
          'Octombrie',
          'Noiembrie',
          'Decembrie',
        ],
        shortMonths: ['Ian', 'Feb', 'Mar', 'Apr', 'Mai', 'Iun', 'Iul', 'Aug', 'Sep', 'Oct', 'Noi', 'Dec'],
        days: ['Duminică', 'Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri', 'Sâmbătă'],
        shortDays: ['Dum', 'Lun', 'Mar', 'Mie', 'Joi', 'Vin', 'Sâm'],
        toolbar: {
          exportToSVG: 'Descarcă SVG',
          exportToPNG: 'Descarcă PNG',
          exportToCSV: 'Descarcă CSV',
          menu: 'Meniu',
          selection: 'Selecție',
          selectionZoom: 'Zoom pe selecție',
          zoomIn: 'Mărire',
          zoomOut: 'Micșorare',
          pan: 'Mutare',
          reset: 'Resetează zoom-ul',
        },
      },
    },
    {
      name: 'pl',
      options: {
        months: [
          'Styczeń',
          'Luty',
          'Marzec',
          'Kwiecień',
          'Maj',
          'Czerwiec',
          'Lipiec',
          'Sierpień',
          'Wrzesień',
          'Październik',
          'Listopad',
          'Grudzień',
        ],
        shortMonths: ['Sty', 'Lu', 'Mar', 'Kwi', 'Maj', 'Cze', 'Lip', 'Sie', 'Wr', 'Paź', 'Lis', 'Gru'],
        days: ['Niedziela', 'Poniedziałek', 'Wtorek', 'Środa', 'Czwartek', 'Piątek', 'Sobota'],
        shortDays: ['Nie', 'Pon', 'Wt', 'Śr', 'Cz', 'Pi', 'So'],
        toolbar: {
          exportToSVG: 'Pobierz SVG',
          exportToPNG: 'Pobierz PNG',
          exportToCSV: 'Pobierz CSV',
          menu: 'Menu',
          selection: 'Wybór',
          selectionZoom: 'Powiększ wybór',
          zoomIn: 'Powiększ',
          zoomOut: 'Pomniejsz',
          pan: 'Przesuń',
          reset: 'Resetuj powiększenie',
        },
      },
    },
  ];
}
