{
 "title": "[gge-tracker] Scraping KPI",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Total Players Created (24h)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\r\n  sum_over_time(\r\n    {job=\"generic-fill-process\"} \r\n    | json \r\n    | unwrap playersCreated \r\n    [24h]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Active Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"generic-fill-process\"} | json | line_format \"{{.server}}\""
    }
   ]
  },
  {
   "title": "Critical Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"generic-fill-process\"} | json | line_format \"{{.criticalErrors}}\""
    }
   ]
  },
  {
   "title": "Players Created",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"generic-fill-process\"}\r\n| json\r\n| __error__=\"\""
    }
   ]
  },
  {
   "title": "Players Alliance Updated",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"generic-fill-process\"}\r\n| json\r\n| __error__=\"\""
    }
   ]
  },
  {
   "title": "Alliances Created",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"generic-fill-process\"}\r\n| json\r\n| __error__=\"\""
    }
   ]
  },
  {
   "title": "Alliances Updated",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"generic-fill-process\"}\r\n| json\r\n| __error__=\"\""
    }
   ]
  },
  {
   "title": "Scraping Duration per Server",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"generic-fill-process\"} \r\n| json "
    }
   ]
  },
  {
   "title": "Average Duration per Server",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg by (server) (\r\n  avg_over_time(\r\n    {job=\"generic-fill-process\"} \r\n    | json \r\n    | unwrap durationMs \r\n    [1h]\r\n  )\r\n)"
    }
   ]
  }
 ]
}