{
 "title": "[gge-tracker] Scraping KPI (dev)",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Active Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT server) FROM logs.scrapes WHERE $__timeFilter(timestamp);"
    }
   ]
  },
  {
   "title": "Critical Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(criticalErrors) FROM logs.scrapes WHERE $__timeFilter(timestamp);"
    }
   ]
  },
  {
   "title": "Total Players Managed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(playerCount) FROM logs.scrapes WHERE $__timeFilter(timestamp) GROUP BY server"
    }
   ]
  },
  {
   "title": "Total Alliances Managed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(allianceCount) FROM logs.scrapes WHERE $__timeFilter(timestamp) GROUP BY server"
    }
   ]
  },
  {
   "title": "Total Players Created",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT playersCreated FROM logs.scrapes WHERE $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "Total Alliances Created",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT alliancesCreated FROM logs.scrapes WHERE $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "Players Created",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT SUM(playersCreated) AS totalPlayers, server FROM logs.scrapes WHERE $__timeFilter(timestamp) GROUP BY server ORDER BY totalPlayers DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Players Alliance Updated",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(playersAllianceUpdated) AS totalPlayers,\r\n  server\r\nFROM logs.scrapes\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY server\r\nORDER BY totalPlayers DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Alliances Created",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(alliancesCreated) AS totalPlayers,\r\n  server\r\nFROM logs.scrapes\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY server\r\nORDER BY totalPlayers DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Alliances Updated",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(alliancesUpdated) AS totalPlayers,\r\n  server\r\nFROM logs.scrapes\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY server\r\nORDER BY totalPlayers DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Activated Scraping Services over time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "WITH \r\n    10 AS resolution_step\r\nSELECT\r\n    toStartOfInterval(slice_time, INTERVAL resolution_step SECOND) AS time,\r\n    count() AS active_servers\r\nFROM (\r\n    SELECT\r\n        arrayJoin(\r\n            arrayMap(\r\n                x -> toDateTime(toStartOfInterval(startTime, INTERVAL resolution_step SECOND) + (x * resolution_step)),\r\n                range(0, toUInt32(dateDiff('second', startTime, timestamp) / resolution_step) + 1)\r\n            )\r\n        ) AS slice_time\r\n    FROM logs.scrapes\r\n    WHERE timestamp >= $__fromTime AND startTime <= $__toTime\r\n)\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Max Scraping Duration per Server",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    server,\r\n    timestamp,\r\n    (MAX(durationMs)/1000/60) AS maxDuration\r\nFROM logs.scrapes\r\nWHERE timestamp >= $__fromTime AND timestamp <= $__toTime\r\nGROUP BY timestamp, server"
    }
   ]
  },
  {
   "title": "Number of Players per Server",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    server,\r\n    timestamp,\r\n    MAX(playerCount) AS playerCount\r\nFROM logs.scrapes\r\nWHERE timestamp >= $__fromTime AND timestamp <= $__toTime\r\nGROUP BY timestamp, server"
    }
   ]
  }
 ]
}