export const HIGHSCORES_TYPES: Record<string, string> = {
  SCORING_SYSTEM_COLLECTOR: 'collector',
  SCORING_SYSTEM_MIGHT: 'might',
  SCORING_SYSTEM_RANK_SWAP: 'rankSwap',
};

export const TEMP_SERVER_SETTINGS = [
  {
    settingID: '8',
    presetIDs: '31',
    peaceDuration: '7200',
    scoringSystem: 'might',
    hasDailyRanking: '1',
    startCurrencyAmount: '-1',
    currencyLootFactorMin: '0',
    rewardSetID: '4',
  },
  {
    settingID: '9',
    presetIDs: '31,32',
    peaceDuration: '7200',
    scoringSystem: 'might',
    hasDailyRanking: '1',
    startCurrencyAmount: '-1',
    currencyLootFactorMin: '0',
    rewardSetID: '4',
  },
  {
    settingID: '10',
    presetIDs: '31,39,32',
    peaceDuration: '0',
    scoringSystem: 'collector',
    hasDailyRanking: '1',
    startCurrencyAmount: '5000',
    currencyLootFactorMin: '10',
    currencyID: '108',
    boosterCurrencyID: '109',
    boosterCurrencyValue: '1',
    boosterCurrencyLimit: '5',
    currencyLootFactorMax: '0.2',
    boosterCurrencyPackageID: '1359',
    rewardSetID: '4',
  },
  {
    settingID: '11',
    presetIDs: '31,39',
    peaceDuration: '0',
    scoringSystem: 'collector',
    hasDailyRanking: '1',
    startCurrencyAmount: '5000',
    currencyLootFactorMin: '10',
    currencyID: '108',
    boosterCurrencyID: '109',
    boosterCurrencyValue: '1',
    boosterCurrencyLimit: '5',
    currencyLootFactorMax: '0.2',
    boosterCurrencyPackageID: '1359',
    rewardSetID: '4',
  },
  {
    settingID: '12',
    presetIDs: '31,39,33',
    peaceDuration: '0',
    scoringSystem: 'collector',
    hasDailyRanking: '1',
    startCurrencyAmount: '5000',
    currencyLootFactorMin: '10',
    currencyID: '108',
    boosterCurrencyID: '109',
    boosterCurrencyValue: '1',
    boosterCurrencyLimit: '5',
    currencyLootFactorMax: '0.2',
    boosterCurrencyPackageID: '1359',
    rewardSetID: '4',
  },
  {
    settingID: '13',
    presetIDs: '31,39,32',
    peaceDuration: '0',
    scoringSystem: 'rankSwap',
    hasDailyRanking: '1',
    startCurrencyAmount: '-1',
    currencyLootFactorMin: '0',
    rewardSetID: '4',
  },
  {
    settingID: '14',
    presetIDs: '31,39,32',
    peaceDuration: '0',
    scoringSystem: 'rankSwap',
    hasDailyRanking: '1',
    startCurrencyAmount: '-1',
    currencyLootFactorMin: '0',
    rewardSetID: '6',
  },
  {
    settingID: '16',
    presetIDs: '40',
    peaceDuration: '0',
    scoringSystem: 'collector',
    hasDailyRanking: '1',
    startCurrencyAmount: '50000',
    currencyLootFactorMin: '10',
    currencyID: '108',
    boosterCurrencyID: '109',
    boosterCurrencyValue: '1',
    boosterCurrencyLimit: '5',
    currencyLootFactorMax: '0.2',
    boosterCurrencyPackageID: '1359',
    rewardSetID: '5',
  },
  {
    settingID: '17',
    presetIDs: '31,39',
    peaceDuration: '0',
    scoringSystem: 'collector',
    hasDailyRanking: '1',
    startCurrencyAmount: '5000',
    currencyLootFactorMin: '10',
    currencyID: '108',
    boosterCurrencyID: '109',
    boosterCurrencyValue: '1',
    boosterCurrencyLimit: '5',
    currencyLootFactorMax: '0.2',
    boosterCurrencyPackageID: '1359',
    rewardSetID: '7',
  },
  {
    settingID: '18',
    presetIDs: '40',
    peaceDuration: '0',
    scoringSystem: 'collector',
    hasDailyRanking: '1',
    startCurrencyAmount: '50000',
    currencyLootFactorMin: '10',
    currencyID: '108',
    boosterCurrencyID: '109',
    boosterCurrencyValue: '1',
    boosterCurrencyLimit: '5',
    currencyLootFactorMax: '0.2',
    boosterCurrencyPackageID: '1359',
    rewardSetID: '8',
  },
  {
    settingID: '19',
    presetIDs: '31,39,32',
    peaceDuration: '0',
    scoringSystem: 'rankSwap',
    hasDailyRanking: '1',
    startCurrencyAmount: '-1',
    currencyLootFactorMin: '0',
    rewardSetID: '9',
  },
  {
    settingID: '20',
    presetIDs: '31,32',
    peaceDuration: '0',
    scoringSystem: 'might',
    hasDailyRanking: '1',
    startCurrencyAmount: '-1',
    currencyLootFactorMin: '0',
    rewardSetID: '10',
  },
  {
    settingID: '21',
    presetIDs: '31,39',
    peaceDuration: '0',
    scoringSystem: 'collector',
    hasDailyRanking: '1',
    startCurrencyAmount: '5000',
    currencyLootFactorMin: '10',
    currencyID: '108',
    boosterCurrencyID: '109',
    boosterCurrencyValue: '1',
    boosterCurrencyLimit: '5',
    currencyLootFactorMax: '0.2',
    boosterCurrencyPackageID: '1359',
    rewardSetID: '11',
  },
  {
    settingID: '22',
    presetIDs: '40',
    peaceDuration: '0',
    scoringSystem: 'collector',
    hasDailyRanking: '1',
    startCurrencyAmount: '50000',
    currencyLootFactorMin: '10',
    currencyID: '108',
    boosterCurrencyID: '109',
    boosterCurrencyValue: '1',
    boosterCurrencyLimit: '5',
    currencyLootFactorMax: '0.2',
    boosterCurrencyPackageID: '1359',
    rewardSetID: '12',
  },
  {
    settingID: '23',
    presetIDs: '31,39,32',
    peaceDuration: '0',
    scoringSystem: 'rankSwap',
    hasDailyRanking: '1',
    startCurrencyAmount: '-1',
    currencyLootFactorMin: '0',
    rewardSetID: '13',
  },
  {
    settingID: '24',
    presetIDs: '31,32',
    peaceDuration: '0',
    scoringSystem: 'might',
    hasDailyRanking: '1',
    startCurrencyAmount: '-1',
    currencyLootFactorMin: '0',
    rewardSetID: '14',
  },
];

export const EVENTTYPE_TEMPSERVER_ID = 106;
