######################################################################################
#                                     __                        __                   #
#      ____   ____   ____           _/  |_____________    ____ |  | __ ___________   #
#     / ___\ / ___\_/ __ \   ______ \   __\_  __ \__  \ _/ ___\|  |/ // __ \_  __ \  #
#    / /_/  > /_/  >  ___/  /_____/  |  |  |  | \// __ \\  \___|    <\  ___/|  | \/  #
#    \___  /\___  / \___  >          |__|  |__|  (____  /\___  >__|_ \\___  >__|     #
#   /_____//_____/      \/                            \/     \/     \/    \/         #
#                                                                                    #
#                     This file is part of the gge-tracker project.                  #
#        Copyrights (c) 2025 - gge-tracker.com & gge-tracker contributors            #
#                                                                                    #
######################################################################################

FROM node:20

WORKDIR /app

RUN apt-get update && apt-get install -y \
    ca-certificates \
    fonts-freefont-ttf \
    libasound2 \
    libfreetype6 \
    libgconf-2-4 \
    libgdk-pixbuf2.0-dev \
    libgtk-3-dev \
    libharfbuzz0b \
    libnotify-dev \
    libnss3 \
    libxss-dev \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install \
    && npx puppeteer browsers install chrome

ENV REDIS_URL=redis://redis-server:6379
EXPOSE 3000

ENV HEADER="[DEV]"

CMD ["npx", "nodemon"]

