export enum RouteErrorMessagesEnum {
  // Generic Messages
  GenericBadRequest = 'Bad Request',
  GenericCreated = 'Created',
  GenericForbidden = 'Forbidden',
  GenericInternalServerError = 'An internal server error occurred. Please try again later.',
  GenericNotFound = 'Not Found',
  GenericOk = 'OK',
  GenericUnauthorized = 'Unauthorized',
  GenericUnknownStatus = 'Unknown Status',
  // Specific Messages
  AllianceNotFound = 'Alliance not found',
  AssetNotFound = 'Asset not found',
  InvalidAllianceId = 'Invalid alliance ID',
  InvalidAllianceName = 'Invalid alliance name',
  InvalidAssetExtension = 'Invalid asset extension',
  InvalidAssetName = 'Invalid asset name',
  InvalidAttackCooldown = 'Invalid attack cooldown',
  InvalidCastleId = 'Invalid castle ID',
  InvalidDivisionId = 'Invalid division ID',
  InvalidDuration = 'Invalid duration',
  InvalidEventId = 'Invalid event ID',
  InvalidEventName = 'Invalid event name',
  InvalidEventType = 'Invalid event type',
  InvalidFlatDateFormat = 'Invalid date format. Please use YYYY-MM-DDTHH:00:00.000Z',
  InvalidInput = 'Invalid input',
  InvalidKingdomId = 'Invalid kingdom ID',
  InvalidLanguage = 'Invalid language parameter',
  InvalidPlayerId = 'Invalid player ID',
  InvalidPlayerName = 'Invalid player name',
  InvalidPosition = 'Invalid position',
  InvalidServer = 'Invalid server',
  InvalidSubdivisionId = 'Invalid subdivision ID',
  MissingLanguage = 'Language parameter is required',
  MissingParameter = 'Missing required parameter',
  PlayerNotFound = 'Player not found',
  RouteMustBeNonEmpty = 'Route must be a non-empty string',
  UnavailableForSpecialServers = 'This feature is unavailable for this server',
}
