/**
 * Enum representing the available GGE Tracker server identifiers.
 *
 * Each value corresponds to a specific game server region or type.
 * These identifiers are used to specify which server to interact with
 * when making API requests or handling server-specific logic.
 */
export enum GgeTrackerServersEnum {
  ARAB1 = 'ARAB1',
  AU1 = 'AU1',
  BR1 = 'BR1',
  CZ1 = 'CZ1',
  DE1 = 'DE1',
  ES1 = 'ES1',
  FR1 = 'FR1',
  GLOBAL = 'GLOBAL',
  HANT1 = 'HANT1',
  CN1 = 'CN1',
  HU1 = 'HU1',
  HU2 = 'HU2',
  IN1 = 'IN1',
  INT1 = 'INT1',
  INT2 = 'INT2',
  INT3 = 'INT3',
  IT1 = 'IT1',
  NL1 = 'NL1',
  PL1 = 'PL1',
  PT1 = 'PT1',
  RO1 = 'RO1',
  RU1 = 'RU1',
  SA1 = 'SA1',
  TR1 = 'TR1',
  US1 = 'US1',
  GR1 = 'GR1',
  ASIA = 'ASIA',
  ES2 = 'ES2',
  LT1 = 'LT1',
  SKN1 = 'SKN1',
  BG1 = 'BG1',
  SK1 = 'SK1',
  GB1 = 'GB1',
  KR1 = 'KR1',
  JP1 = 'JP1',
  HIS1 = 'HIS1',
  AE1 = 'AE1',
  EG1 = 'EG1',
  WORLD1 = 'WORLD1',
  E4K_HANT1 = 'E4K_HANT1',
  E4K_BR1 = 'E4K_BR1',
  E4K_FR1 = 'E4K_FR1',
  E4K_DE1 = 'E4K_DE1',
  E4K_DE2 = 'E4K_DE2',
  E4K_US1 = 'E4K_US1',
  E4K_INT2 = 'E4K_INT2',
  E4K_CN1 = 'E4K_CN1',
}
