name: gge-tracker Projects CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read
jobs:
  # ---------------------------
  # Backend CI
  # ---------------------------
  gge_tracker_backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gge-tracker-backend-api
    steps:
      - uses: actions/checkout@v3
      - name: Detect backend changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'gge-tracker-backend-api/**'
      - name: Skip if no backend changes
        if: steps.changes.outputs.backend != 'true'
        run: echo "No backend changes detected, skipping backend job." && exit 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build TypeScript + Swagger
        run: |
          npx tsc
          npx swagger-jsdoc -d ./src/documentation.js
      - name: Docker Build (check only)
        run: docker build --target build -t backend-check -f Dockerfile.prod .
  # ---------------------------
  # Frontend CI
  # ---------------------------
  gge_tracker_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gge-tracker-frontend
    steps:
      - uses: actions/checkout@v3
      - name: Detect frontend changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'gge-tracker-frontend/**'
      - name: Skip if no frontend changes
        if: steps.changes.outputs.frontend != 'true'
        run: echo "No frontend changes detected, skipping frontend job." && exit 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Angular Build
        run: npm run build -- --output-path=dist --configuration=production
      - name: Docker Build
        run: docker build --target build -t frontend-check .
